### ISSUE TITLE
what license would you use?

### ISSUE THREAD

**Issue by abotzki** [Mathelab/IntLIM#10]
Hi again, I resumed working on packaging of IntLIM for bioconda. One prerequisite is to provide a valid license in the github repository which allows redistribution. Examples on license can be found here: https://opensource.org/licenses
Thanks.

**Comment by Mathelab** [comment]
Hello Alexander,
IntLIM is under a GPL-2 license, this is noted in the DESCRIPTION file.
Best,
Ewy
