### ISSUE TITLE
Error when loading file in the Web App

### ISSUE THREAD

**Issue by vibbits** [Mathelab/IntLIM#4]
Hello! I am happy to try out your tool, but when im uploading my input files in the web app (https://intlim.bmi.osumc.edu/), I get this error: 

**_Error: File /tmp/RtmpFqQEgw/6c140f765c4913146602d4df/3 does not existFile /tmp/RtmpFqQEgw/6c140f765c4913146602d4df/NA does not existFile /tmp/RtmpFqQEgw/6c140f765c4913146602d4df/NA does not exist_**

UPODATE:
I managed to solve the issue. 
One needs to make sure that the input.csv file has ONLY 2 COLUMNS!!! I had an error because I had a third empty column....

**Comment by jalalsiddiqui** [comment]
Glad to know that you could solve it.
