### ISSUE TITLE
formal release of code

### ISSUE THREAD

**Issue by vibbits** [Mathelab/IntLIM#5]
Hi, in order to arrive at a more reproducible setup of our data analysis tools, we are striving to use tools which have fixed code basis. My colleague Oren recently used your tool and it gives interesting results. We suspect that we could publish the results later on. in order to do so, we would very much appreciate if you could create a formal release of your software in your repository. This would allow us to specifiy the version we have used in our methods description and any other reproducible image we will put together e.g. in biocontainers or similar.
Thanks a lot. cheers Alex

**Comment by jalalsiddiqui** [comment]
Thanks for letting us know.  I have created a formal release of IntLIM.  v.1.1.0
