### ISSUE TITLE
saving output plots

### ISSUE THREAD

**Issue by vibbits** [Mathelab/IntLIM#6]
Hello, I have been using IntLIM, but I am struggling to save all outputs into one zip file:
IntLIM::OutputData(inputData=inputDatafilt,filename="~/FilteredData.zip")
OutputResults(inputResults=myres,filename="~/MyResults.csv")

These works fine to save the filtered data and the top genes / metabolites. But not saving the plots. 
boo <- IntLIM::CorrHeatmap(myres)
IntLIM::OutputData(inputData=boo,filename="~/FilteredData.zip")

Does not work.. Your help will be highly appreciated. 
Cheers!

**Comment by Mathelab** [comment]
We are currently working on this and will add a function to create a static heatmap plot that can be saved as a pdf.

**Comment by jalalsiddiqui** [comment]
We have added a way to obtain a static version of the heatmap right now.  The CorrHeatmap function allows one to obtain static heatmap.2 version of the gene-metabolite heatmap.  There is a 'static' option which can be set to 'TRUE'.  

hm = CorrHeatmap(myres, static=TRUE)

We are implementing functions in the Shiny app that will allow for downloading of the resulting heatmap.  

Hope this helps.

**Comment by jalalsiddiqui** [comment]
I have also added an html.file option to the CorrHeatmap function that allows the user to download an HTML interactive heatmap.  This can be done with the non-static option.

**Comment by jalalsiddiqui** [comment]
The Shiny app now allows for downloading a pdf version of the heatmap
